///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest80
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest80Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("764b759f-ac15-4eb9-a885-1b84e9c0da7e")]
    public partial class MyTest80Repository : RepoGenBaseFolder
    {
        static MyTest80Repository instance = new MyTest80Repository();
        MyTest80RepositoryFolders.RxMainFrameAppFolder _rxmainframe;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest80Repository element repository.
        /// </summary>
        [RepositoryFolder("764b759f-ac15-4eb9-a885-1b84e9c0da7e")]
        public static MyTest80Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest80Repository() 
            : base("MyTest80Repository", "/", null, 0, false, "764b759f-ac15-4eb9-a885-1b84e9c0da7e", ".\\RepositoryImages\\MyTest80Repository764b759f.rximgres")
        {
            _rxmainframe = new MyTest80RepositoryFolders.RxMainFrameAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("764b759f-ac15-4eb9-a885-1b84e9c0da7e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("2173d82e-6a35-4788-b335-1b348aa09a62")]
        public virtual MyTest80RepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest80RepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("2173d82e-6a35-4788-b335-1b348aa09a62")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            MyTest80RepositoryFolders.RxTabIntroductionFolder _rxtabintroduction;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "2173d82e-6a35-4788-b335-1b348aa09a62", "")
            {
                _rxtabintroduction = new MyTest80RepositoryFolders.RxTabIntroductionFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2173d82e-6a35-4788-b335-1b348aa09a62")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2173d82e-6a35-4788-b335-1b348aa09a62")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RxTabIntroduction folder.
            /// </summary>
            [RepositoryFolder("20ce308f-b674-4482-b2a4-316ac82356e8")]
            public virtual MyTest80RepositoryFolders.RxTabIntroductionFolder RxTabIntroduction
            {
                get { return _rxtabintroduction; }
            }
        }

        /// <summary>
        /// The RxTabIntroductionFolder folder.
        /// </summary>
        [RepositoryFolder("20ce308f-b674-4482-b2a4-316ac82356e8")]
        public partial class RxTabIntroductionFolder : RepoGenBaseFolder
        {
            BtnSubmitUserNameInfoClass _btnsubmitusernameInfo;
            RxLinkBtnResetInfoClass _rxlinkbtnresetInfo;
            TxtUserNameInfoClass _txtusernameInfo;

            /// <summary>
            /// Creates a new RxTabIntroduction  folder.
            /// </summary>
            public RxTabIntroductionFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabIntroduction", "?/?/tabpage[@controlname='RxTabIntroduction']", parentFolder, 30000, null, false, "20ce308f-b674-4482-b2a4-316ac82356e8", "")
            {
                _btnsubmitusernameInfo = new BtnSubmitUserNameInfoClass(this);
                _rxlinkbtnresetInfo = new RxLinkBtnResetInfoClass(this);
                _txtusernameInfo = new TxtUserNameInfoClass(this);
            }

            /// <summary>
            /// The BtnSubmitUserNameInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("2a6e4802-e489-4da5-87c1-0811015d1a7e")]
            public class BtnSubmitUserNameInfoClass : RepoItemInfo
            {
                /// <summary>
                /// BtnSubmitUserNameInfoClass class constructor.
                /// </summary>
                public BtnSubmitUserNameInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "BtnSubmitUserName", "button[@controlname='btnSubmitUserName']", 30000, null, "2a6e4802-e489-4da5-87c1-0811015d1a7e")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("21fe4f7f-f05a-42c7-ae79-3cd9666888a2")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("21fe4f7f-f05a-42c7-ae79-3cd9666888a2");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("21fe4f7f-f05a-42c7-ae79-3cd9666888a2")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("21fe4f7f-f05a-42c7-ae79-3cd9666888a2", cropRect);
                }
            }

            /// <summary>
            /// The RxLinkBtnResetInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("4dd554ad-39d4-4ae8-a62a-ab23ade9501c")]
            public class RxLinkBtnResetInfoClass : RepoItemInfo
            {
                /// <summary>
                /// RxLinkBtnResetInfoClass class constructor.
                /// </summary>
                public RxLinkBtnResetInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "RxLinkBtnReset", "link[@controlname='RxLinkBtnReset']", 30000, null, "4dd554ad-39d4-4ae8-a62a-ab23ade9501c")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("bf6ff4c4-c8ab-4db9-a0c9-b8f539bb3197")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("bf6ff4c4-c8ab-4db9-a0c9-b8f539bb3197");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("bf6ff4c4-c8ab-4db9-a0c9-b8f539bb3197")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("bf6ff4c4-c8ab-4db9-a0c9-b8f539bb3197", cropRect);
                }
            }

            /// <summary>
            /// The TxtUserNameInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("20dfe008-6756-43d8-8da2-2b3741f88e71")]
            public class TxtUserNameInfoClass : RepoItemInfo
            {
                /// <summary>
                /// TxtUserNameInfoClass class constructor.
                /// </summary>
                public TxtUserNameInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "TxtUserName", "text[@controlname='txtUserName']", 30000, null, "20dfe008-6756-43d8-8da2-2b3741f88e71")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("b53d7bb7-1491-426a-b99f-42d8b3e7db2a")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("b53d7bb7-1491-426a-b99f-42d8b3e7db2a");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("b53d7bb7-1491-426a-b99f-42d8b3e7db2a")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("b53d7bb7-1491-426a-b99f-42d8b3e7db2a", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("20ce308f-b674-4482-b2a4-316ac82356e8")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("20ce308f-b674-4482-b2a4-316ac82356e8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item.
            /// </summary>
            [RepositoryItem("2a6e4802-e489-4da5-87c1-0811015d1a7e")]
            public virtual Ranorex.Button BtnSubmitUserName
            {
                get
                {
                    return _btnsubmitusernameInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item info.
            /// </summary>
            [RepositoryItemInfo("2a6e4802-e489-4da5-87c1-0811015d1a7e")]
            public virtual BtnSubmitUserNameInfoClass BtnSubmitUserNameInfo
            {
                get
                {
                    return _btnsubmitusernameInfo;
                }
            }

            /// <summary>
            /// The RxLinkBtnReset item.
            /// </summary>
            [RepositoryItem("4dd554ad-39d4-4ae8-a62a-ab23ade9501c")]
            public virtual Ranorex.Link RxLinkBtnReset
            {
                get
                {
                    return _rxlinkbtnresetInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The RxLinkBtnReset item info.
            /// </summary>
            [RepositoryItemInfo("4dd554ad-39d4-4ae8-a62a-ab23ade9501c")]
            public virtual RxLinkBtnResetInfoClass RxLinkBtnResetInfo
            {
                get
                {
                    return _rxlinkbtnresetInfo;
                }
            }

            /// <summary>
            /// The TxtUserName item.
            /// </summary>
            [RepositoryItem("20dfe008-6756-43d8-8da2-2b3741f88e71")]
            public virtual Ranorex.Text TxtUserName
            {
                get
                {
                    return _txtusernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtUserName item info.
            /// </summary>
            [RepositoryItemInfo("20dfe008-6756-43d8-8da2-2b3741f88e71")]
            public virtual TxtUserNameInfoClass TxtUserNameInfo
            {
                get
                {
                    return _txtusernameInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
